wandb_version: 1

epoch:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 8
lr:
  desc: null
  value: 1.0e-05
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.6
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701336845.090778
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.9.16
      5: 0.15.6
      6: 4.35.2
      8:
      - 5
